library(dplyr)
library(tidyverse)

setwd("dir")

# ============================================================================
# DATA INPUT AND LOADING
# ============================================================================

# Load chimera data - merged output files from all samples
# Original files: ${samples}_all_chimera_alongHIMs_IE.txt
# Generated by: WorkflowBowBlast with blastn=TRUE option (https://github.com/HeloiseMuller/WorkflowBowBlast)
chimera <- read.csv("all_chimera.csv", header = TRUE, sep = ";")

# Load depth data - merged coverage information for all samples
# Original files: ${samples}_coverage_positions
# Generated by: CovWindows software (https://github.com/HeloiseMuller/CovWindows)
# Command: CovWindows/build/CovWindows -w Segments_coordinates.txt -f -c ${samples}_trimmed_vs_${wasp}_coverage_positions -d -o ${samples}_coverage_positions
# Coverage input files from: WorkflowBowBlast with bowtie2=TRUE and coverage=TRUE options
depth <- read.csv("all_depth.csv", header = TRUE, sep = ";")

# ============================================================================
# DATA MANIPULATION: INTEGRATION COUNTS BY SEGMENT
# ============================================================================

# Count the number of integrations for each sample and segment combination
Chim_seg <- group_by(chimera, sample, Segment) %>% 
  summarise(int=n())

# Merge chimera integration counts with depth data
ChimD <- left_join(depth, Chim_seg, by = c("sample", "Segment")) %>% 
  select(sample, wasp, host, Segment, int, depth)

# ============================================================================
# PROBLEM RESOLUTION: SEGMENT 10 AND SEGMENT 17 AMBIGUITY
# ============================================================================
# ISSUE: Identical HIM sequences in Segment 10 and Segment 17 cause integration 
# assignments to merge together for Cotesia icipe (Ci), C. sesamiae_mombasa (CsM), 
# and C. sesamiae_kitale (CsK).
# 
# SOLUTION: Redistribute merged integrations proportionally based on sequencing 
# depth on each segment. This approach assumes integrations are distributed 
# according to the relative representation of each segment in the sequencing data.

# ============================================================================
# CORRECTION FOR COTESIA ICIPE (Ci)
# ============================================================================

ChimD_10_17 <- dplyr::filter(ChimD, wasp=="cotesia_icipe", Segment=="Segment_10"|Segment=="Segment_17")

# Sample 1 (SfCi1): redistribute integrations between Segment 10 and 17 
# based on relative depth ratios
int1_10 = (ChimD_10_17[3,6]/(ChimD_10_17[4,6]+ChimD_10_17[3,6]))*(ChimD_10_17[4,5]+ChimD_10_17[3,5])
int1_17 = (ChimD_10_17[4,6]/(ChimD_10_17[4,6]+ChimD_10_17[3,6]))*(ChimD_10_17[4,5]+ChimD_10_17[3,5])

# Sample 2 (SfCi2): redistribute integrations between Segment 10 and 17
int2_10 = (ChimD_10_17[1,6]/(ChimD_10_17[2,6]+ChimD_10_17[1,6]))*(ChimD_10_17[2,5]+ChimD_10_17[1,5])
int2_17 = (ChimD_10_17[2,6]/(ChimD_10_17[2,6]+ChimD_10_17[1,6]))*(ChimD_10_17[2,5]+ChimD_10_17[1,5])

# Update the integration counts in the main dataset with corrected values
ChimD <- mutate(ChimD, 
                int=if_else((sample=="SfCi2" & Segment=="Segment_10"), int2_10, int),
                int=if_else((sample=="SfCi2" & Segment=="Segment_17"), int2_17, int),
                int=if_else((sample=="SfCi1" & Segment=="Segment_10"), int1_10, int),
                int=if_else((sample=="SfCi1" & Segment=="Segment_17"), int1_17, int))  

rm(ChimD_10_17)

# ============================================================================
# CORRECTION FOR COTESIA SESAMIAE_MOMBASA (CsM)
# ============================================================================

ChimD_10_17 <- filter(ChimD, wasp=="cotesia_sesamiae_mombasa", Segment=="Segment_10"|Segment=="Segment_17") %>% 
  mutate_all(~replace(., is.na(.), 0))

# Sample 1 (BfCsCo2): redistribute integrations
int1_10 = (ChimD_10_17[3,6]/(ChimD_10_17[4,6]+ChimD_10_17[3,6]))*(ChimD_10_17[4,5]+ChimD_10_17[3,5])
int1_17 = (ChimD_10_17[4,6]/(ChimD_10_17[4,6]+ChimD_10_17[3,6]))*(ChimD_10_17[4,5]+ChimD_10_17[3,5])

# Sample 2 (BfCsCo1): redistribute integrations
int2_10 = (ChimD_10_17[1,6]/(ChimD_10_17[2,6]+ChimD_10_17[1,6]))*(ChimD_10_17[2,5]+ChimD_10_17[1,5])
int2_17 = (ChimD_10_17[2,6]/(ChimD_10_17[2,6]+ChimD_10_17[1,6]))*(ChimD_10_17[2,5]+ChimD_10_17[1,5])

# Sample 3 (BfCsCo3): redistribute integrations
int3_10 = (ChimD_10_17[5,6]/(ChimD_10_17[6,6]+ChimD_10_17[5,6]))*(ChimD_10_17[6,5]+ChimD_10_17[5,5])
int3_17 = (ChimD_10_17[6,6]/(ChimD_10_17[6,6]+ChimD_10_17[5,6]))*(ChimD_10_17[6,5]+ChimD_10_17[5,5])

# Sample 4 (Co1): redistribute integrations
int4_10 = (ChimD_10_17[7,6]/(ChimD_10_17[8,6]+ChimD_10_17[7,6]))*(ChimD_10_17[8,5]+ChimD_10_17[7,5])
int4_17 = (ChimD_10_17[8,6]/(ChimD_10_17[8,6]+ChimD_10_17[7,6]))*(ChimD_10_17[7,5]+ChimD_10_17[8,5])

# Sample 5 (Co2): redistribute integrations
int5_10 = (ChimD_10_17[9,6]/(ChimD_10_17[10,6]+ChimD_10_17[9,6]))*(ChimD_10_17[10,5]+ChimD_10_17[9,5])
int5_17 = (ChimD_10_17[10,6]/(ChimD_10_17[10,6]+ChimD_10_17[9,6]))*(ChimD_10_17[10,5]+ChimD_10_17[9,5])

# Sample 6 (Co3): redistribute integrations
int6_10 = (ChimD_10_17[11,6]/(ChimD_10_17[12,6]+ChimD_10_17[11,6]))*(ChimD_10_17[12,5]+ChimD_10_17[11,5])
int6_17 = (ChimD_10_17[12,6]/(ChimD_10_17[12,6]+ChimD_10_17[11,6]))*(ChimD_10_17[12,5]+ChimD_10_17[11,5])

# Update the integration counts in the main dataset with corrected values
ChimD <- mutate(ChimD, 
                int=if_else((sample=="BfCsCo1" & Segment=="Segment_10"), int2_10, int),
                int=if_else((sample=="BfCsCo1" & Segment=="Segment_17"), int2_17, int),
                int=if_else((sample=="BfCsCo2" & Segment=="Segment_10"), int1_10, int),
                int=if_else((sample=="BfCsCo2" & Segment=="Segment_17"), int1_17, int), 
                int=if_else((sample=="BfCsCo3" & Segment=="Segment_17"), int3_17, int),
                int=if_else((sample=="BfCsCo3" & Segment=="Segment_10"), int3_10, int),
                int=if_else((sample=="Co1" & Segment=="Segment_17"), int4_17, int),
                int=if_else((sample=="Co1" & Segment=="Segment_17"), int4_17, int),
                int=if_else((sample=="Co2" & Segment=="Segment_10"), int5_10, int),
                int=if_else((sample=="Co2" & Segment=="Segment_17"), int5_17, int),
                int=if_else((sample=="Co3" & Segment=="Segment_10"), int6_10, int),
                int=if_else((sample=="Co3" & Segment=="Segment_17"), int6_17, int)) 

rm(ChimD_10_17)

# ============================================================================
# CORRECTION FOR COTESIA SESAMIAE_KITALE (CsK)
# ============================================================================

ChimD_10_17 <- filter(ChimD, wasp=="cotesia_sesamiae_kitale", Segment=="Segment_10"|Segment=="Segment_17") %>% 
  mutate_all(~replace(., is.na(.), 0))

# Sample 1 (BfCsIn2): redistribute integrations
int1_10 = (ChimD_10_17[3,6]/(ChimD_10_17[4,6]+ChimD_10_17[3,6]))*(ChimD_10_17[4,5]+ChimD_10_17[3,5])
int1_17 = (ChimD_10_17[4,6]/(ChimD_10_17[4,6]+ChimD_10_17[3,6]))*(ChimD_10_17[4,5]+ChimD_10_17[3,5])

# Sample 2 (BfCsIn3): redistribute integrations
int2_10 = (ChimD_10_17[1,6]/(ChimD_10_17[2,6]+ChimD_10_17[1,6]))*(ChimD_10_17[2,5]+ChimD_10_17[1,5])
int2_17 = (ChimD_10_17[2,6]/(ChimD_10_17[2,6]+ChimD_10_17[1,6]))*(ChimD_10_17[2,5]+ChimD_10_17[1,5])

# Sample 3 (BfCsIn1): redistribute integrations
int3_10 = (ChimD_10_17[5,6]/(ChimD_10_17[6,6]+ChimD_10_17[5,6]))*(ChimD_10_17[6,5]+ChimD_10_17[5,5])
int3_17 = (ChimD_10_17[6,6]/(ChimD_10_17[6,6]+ChimD_10_17[5,6]))*(ChimD_10_17[6,5]+ChimD_10_17[5,5])

# Sample 4 (In1): redistribute integrations
int4_10 = (ChimD_10_17[7,6]/(ChimD_10_17[8,6]+ChimD_10_17[7,6]))*(ChimD_10_17[8,5]+ChimD_10_17[7,5])
int4_17 = (ChimD_10_17[8,6]/(ChimD_10_17[8,6]+ChimD_10_17[7,6]))*(ChimD_10_17[7,5]+ChimD_10_17[8,5])

# Sample 5 (In2): redistribute integrations
int5_10 = (ChimD_10_17[9,6]/(ChimD_10_17[10,6]+ChimD_10_17[9,6]))*(ChimD_10_17[10,5]+ChimD_10_17[9,5])
int5_17 = (ChimD_10_17[10,6]/(ChimD_10_17[10,6]+ChimD_10_17[9,6]))*(ChimD_10_17[10,5]+ChimD_10_17[9,5])

# Sample 6 (In3): redistribute integrations
int6_10 = (ChimD_10_17[11,6]/(ChimD_10_17[12,6]+ChimD_10_17[11,6]))*(ChimD_10_17[12,5]+ChimD_10_17[11,5])
int6_17 = (ChimD_10_17[12,6]/(ChimD_10_17[12,6]+ChimD_10_17[11,6]))*(ChimD_10_17[12,5]+ChimD_10_17[11,5])

# Update the integration counts in the main dataset with corrected values
ChimD <- mutate(ChimD, 
                int=if_else((sample=="BfCsIn3" & Segment=="Segment_10"), int2_10, int),
                int=if_else((sample=="BfCsIn3" & Segment=="Segment_17"), int2_17, int),
                int=if_else((sample=="BfCsIn2" & Segment=="Segment_10"), int1_10, int),
                int=if_else((sample=="BfCsIn2" & Segment=="Segment_17"), int1_17, int), 
                int=if_else((sample=="BfCsIn1" & Segment=="Segment_17"), int3_17, int),
                int=if_else((sample=="BfCsIn1" & Segment=="Segment_10"), int3_10, int),
                int=if_else((sample=="In1" & Segment=="Segment_17"), int4_17, int),
                int=if_else((sample=="In1" & Segment=="Segment_17"), int4_17, int),
                int=if_else((sample=="In2" & Segment=="Segment_10"), int5_10, int),
                int=if_else((sample=="In2" & Segment=="Segment_17"), int5_17, int),
                int=if_else((sample=="In3" & Segment=="Segment_10"), int6_10, int),
                int=if_else((sample=="In3" & Segment=="Segment_17"), int6_17, int)) 

rm(ChimD_10_17)

# ============================================================================
# DATA OUTPUT
# ============================================================================

# Export the corrected merged dataset (integrations + depth) to a tab-separated file
# This file can be used for downstream analyses
write.table(ChimD, "chimera_depth.txt", sep='\t', quote = FALSE, row.names = FALSE, col.names = TRUE)

